# You don't have to manually edit this file!
# RLBotGUI has an appearance editor with a nice colorpicker, database of items and more!
# To open it up, simply click the (i) icon next to your bot's name and then click Edit Appearance

[blue_loadout]
# Primary Color selection
team_color_id = 60
# Secondary Color selection
custom_color_id = 0
# Car type (Octane, Merc, etc)
car_id = 23
# Type of decal
decal_id = 0
# Wheel selection
wheels_id = 1565
# Boost selection
boost_id = 35
# Antenna Selection
antenna_id = 0
# Hat Selection
hat_id = 0
# Paint Type (for first color)
paint_finish_id = 1681
# Paint Type (for secondary color)
custom_finish_id = 1681
# Engine Audio Selection
engine_audio_id = 0
# Car trail Selection
trails_id = 3220
# Goal Explosion Selection
goal_explosion_id = 3018

[orange_loadout]
team_color_id = 3
custom_color_id = 0
car_id = 23
decal_id = 0
wheels_id = 1565
boost_id = 35
antenna_id = 0
hat_id = 0
paint_finish_id = 1681
custom_finish_id = 1681
engine_audio_id = 0
trails_id = 3220
goal_explosion_id = 3018

[blue_loadout.paint]
car_paint_id = 12
decal_paint_id = 0
wheels_paint_id = 7	
boost_paint_id = 7
antenna_paint_id = 0
hat_paint_id = 0
trails_paint_id = 2
goal_explosion_paint_id = 0

[orange_loadout.paint]
car_paint_id = 12
decal_paint_id = 0
wheels_paint_id = 14
boost_paint_id = 14
antenna_paint_id = 0
hat_paint_id = 0
trails_paint_id = 14
goal_explosion_paint_id = 0
